import type { Metadata } from "next";
import { Nunito_Sans, Tektur,  } from "next/font/google";

import "./globals.css";
import { ChatPopup } from "@components/shared/modal-chat";

const nunitoFont = Tektur({
  variable: '--font-nunito',
  subsets: ['cyrillic']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoFont.variable} antialiased`}
      >
        {children}
        <ChatPopup />
      </body>
    </html>
  );
}
